version: 2.1

jobs:
  build_images:
    parameters:
      arch:
        type: string
    machine:
      image: ubuntu-2004:202101-04
    resource_class: << parameters.arch >>.medium
    steps:
      - checkout
      - run: curl https://github.com/bcaldwell/ci-scripts/releases/download/latest/linux_<< parameters.arch >>64 > ci-scripts
      - run: sudo chmod +x ci-scripts && sudo mv ci-scripts /usr/local/bin/
      - run: pip install pyyaml
      - run: python3 .circleci/build_images.py << parameters.arch >>64

workflows:
  version: 2
  build_images:
    jobs:
      - build_images:
          matrix:
            parameters:
              arch: ["arm", "amd"]
          context: docker
