# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_images:
    docker:
      - image: benjamincaldwell/ci-scripts
    # Run the welcome/run job in its own container
    steps:
      - checkout
      - setup_remote_docker

      - run: apk add python3 py3-yaml
      - run: python3 .circleci/build_images.py

workflows:
  version: 2
  build_images:
    jobs:
      - build_images:
          context: docker
