version: 2.1

jobs:
  build_images_amd:
    docker:
      - image: benjamincaldwell/ci-scripts
    steps:
      - checkout
      - setup_remote_docker

      - run: apk add python3 py3-yaml
      - run: python3 .circleci/build_images.py amd64

  build_images_arm:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: curl https://github.com/bcaldwell/ci-scripts/releases/download/latest/linux_arm64 > ci-scripts
      - run: sudo chmod +x ci-scripts && sudo mv ci-scripts /usr/local/bin/
      - run: python3 .circleci/build_images.py arm64

workflows:
  version: 2
  build_images:
    jobs:
      - build_images_amd:
          context: docker
      - build_images_arm:
          context: docker
